id: I67188018
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:46.102178
last_modified: 2023-01-04 11:31:46.102197
source_metadata:
  collections:
  - Chöje Lingpa Series
  - Works of Tibetan Masters
bases:
  C375:
    title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
      Practice that Unites the Oral, Treasure and Visionary Teachings
    base_file: C375.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
